In [1]:
import pandas as pd
import numpy as np


# load data
"""
dataset url : https://archive.ics.uci.edu/ml/datasets/Airfoil+Self-Noise
"""


def load_data():
    data_file = "data.csv"
    df = pd.read_csv(data_file, delimiter="\t", header=None)

    X = df.iloc[:, :5].to_numpy()
    y = df[5].to_numpy()
    y = y.reshape(-1,1)

    return X, y

In [2]:
X, y = load_data()

In [3]:
from sklearn.model_selection import train_test_split

# split into train test set
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=0)

In [4]:
# using ReLU as activation function
def activation(a):
    return np.maximum(a, 0)

In [5]:
# using mse as cost function
from sklearn.metrics import mean_squared_error as mse
def cost(y_pred, y_true):
   return mse(y_pred, y_true)

In [6]:
def relu_derivative(z):
    return 1 * (z > 0)

In [7]:
sample = X_train[:5, :]
sample

array([[5.00000e+02, 8.40000e+00, 5.08000e-02, 3.96000e+01, 5.66229e-03],
       [2.00000e+03, 1.54000e+01, 5.08000e-02, 7.13000e+01, 2.64269e-02],
       [3.15000e+03, 1.97000e+01, 5.08000e-02, 7.13000e+01, 3.41183e-02],
       [1.00000e+03, 1.12000e+01, 5.08000e-02, 3.96000e+01, 1.50478e-02],
       [2.50000e+03, 1.26000e+01, 1.52400e-01, 7.13000e+01, 4.83159e-02]])

In [8]:
X_train.shape

(1052, 5)

In [9]:
# nn properties

hidden_layer_width = 5
number_of_hidden_layers = 3
n_features = X_train.shape[1]

weights_for_hidden_layers = []
biases_for_hidden_layers = []

# init weights and biases
for _ in range(number_of_hidden_layers):
    w = np.random.normal(size=(n_features, hidden_layer_width))
    weights_for_hidden_layers.append(w)

    b = np.random.normal(size=(hidden_layer_width, 1))
    biases_for_hidden_layers.append(b)

In [10]:
weights_for_hidden_layers[0]

array([[-0.32904012,  0.31616278, -0.49510917, -0.7275853 , -0.28130714],
       [-0.38993569, -1.5758254 ,  0.55200194, -0.64742831,  0.1343612 ],
       [-1.00668363,  0.92943769,  0.14488567, -1.19965484, -0.76715973],
       [ 2.23475548,  0.38893487,  0.40808954,  1.6339929 , -0.85851622],
       [ 0.53521947,  2.42120454,  1.82853556,  0.48403706,  1.07140922]])

In [11]:
biases_for_hidden_layers[0]

array([[ 0.20290826],
       [ 1.09670449],
       [-1.45907768],
       [-0.09395609],
       [ 0.73512238]])

In [48]:
# properties for the output layer
n_output = 1 # since regression
output_weight = np.random.normal(size=(hidden_layer_width, n_output))
output_bias = np.random.normal()

In [49]:
output_weight

array([[ 0.07571491],
       [ 0.52706376],
       [-0.03233443],
       [ 0.61530293],
       [ 0.47310406]])

In [50]:
output_bias

-1.55445440827507

In [69]:
# train the NN

epochs = 1
learning_rate = 0.1

losses = []
for e in range(epochs):
    print(f"epoch = {e + 1}")

    # forward pass
    outputs = []
    for x in X_train:
        x = x.reshape((-1,1))

        a = np.add(np.dot(weights_for_hidden_layers[0].T, x), biases_for_hidden_layers[0])
        a = activation(a)
        for i in range(1, number_of_hidden_layers):
            a = np.add(np.dot(weights_for_hidden_layers[i].T, a), biases_for_hidden_layers[i])
            a = activation(a)

        output = np.add(np.dot(output_weight.T, a), output_bias)
        outputs.append(output[0])

    # backprop
    outputs = np.array(outputs)
    loss = cost(outputs, y_train)
    losses.append(loss)
    print(f"loss = {loss}")

    for i in range(outputs.shape[0]):
        o = outputs[i]
        # last hidden layer output
        a = np.divide(np.subtract(o, output_bias), output_weight)

        # update weight
        f = 2 * np.dot(np.mean(outputs - y_train), a)
        output_weight -= learning_rate * f

        # update bias
        output_bias -= learning_rate * 2 * np.mean(outputs - y_train)

        # now for other layers
        h = number_of_hidden_layers - 2
        while(h >= 0):
            w = weights_for_hidden_layers[h]
            b = biases_for_hidden_layers[h]
            h -= 1




epoch = 1
loss = 1044046732642009.2


(1052, 1)